import Link from 'next/link';

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#050505] text-zinc-50">
      <section className="pt-40 pb-16 px-6 max-w-3xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
        <p className="text-zinc-400 text-sm mb-8">Last updated: August 2026</p>

        <div className="space-y-8 text-zinc-400 leading-relaxed">
          <div>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Clyppr (the &quot;Platform&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform. Clyppr is operated as a two-sided marketplace connecting brands and content creators for performance-based video clip distribution.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white mb-3">2. Eligibility</h2>
            <p>You must be at least 18 years old to use Clyppr. By creating an account, you represent that you meet this requirement and have the legal capacity to enter into a binding agreement.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white mb-3">3. Account Roles</h2>
            <p className="mb-2"><b className="text-white">Creators</b> cut short-form clips from brand-provided footage and distribute them across social platforms to generate views and earn payouts.</p>
            <p className="mb-2"><b className="text-white">Brands (Business)</b> upload video assets, set campaign budgets and CPM rates, and pay only for verified views generated by creators.</p>
            <p>Each account is assigned a single role during onboarding. Role switching requires creating a separate account.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white mb-3">4. Campaigns and Payments</h2>
            <p className="mb-2">Brands fund campaigns in USDC or USDT. Funds are held in escrow during the campaign period. Upon view verification, funds are automatically transferred to creator balances.</p>
            <p className="mb-2">Creators can withdraw their earnings at any time to a compatible crypto wallet. Minimum withdrawal thresholds may apply.</p>
            <p>Clyppr charges a platform fee on completed campaigns. Fee details are displayed before campaign launch.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white mb-3">5. View Verification and Fraud</h2>
            <p>All views are subject to verification through our proprietary fraud detection system. Engagement analysis, velocity checks, and API audits ensure only legitimate human impressions are counted. Views identified as fraudulent will not be paid.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white mb-3">6. Content Guidelines</h2>
            <p className="mb-2">Creators must follow these rules when editing and distributing clips:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>No misleading or deceptive content.</li>
              <li>No content that violates platform terms (TikTok, YouTube, Instagram, X).</li>
              <li>No hate speech, violence, or illegal content.</li>
              <li>Brand assets must be used only within the scope of the active campaign.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white mb-3">7. Intellectual Property</h2>
            <p>Brands retain ownership of their original footage. Creators retain ownership of their edits. By participating in a campaign, creators grant the brand a non-exclusive license to use the created clips for marketing purposes.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white mb-3">8. Termination</h2>
            <p>Clyppr reserves the right to suspend or terminate accounts that violate these terms, engage in fraudulent activity, or harm the platform ecosystem. Terminated accounts forfeit any pending unpaid balances.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white mb-3">9. Limitation of Liability</h2>
            <p>Clyppr is provided &quot;as is&quot; without warranties. We are not liable for indirect, incidental, or consequential damages arising from your use of the Platform.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-white mb-3">10. Changes to Terms</h2>
            <p>We may update these terms at any material time. Continued use of the Platform after changes constitutes acceptance of the new terms.</p>
          </div>
        </div>

        <Link href="/" className="mt-12 inline-block text-white underline">Back to home</Link>
      </section>
    </div>
  );
}
